### ISSUE TITLE
something still requires `monk`

### ISSUE THREAD

**Issue by dcsan** [ratson/monkii#3]
after various other conflicts someone pointed me to this repo, however I am still seeing 

Error: Cannot find module 'monk'

despite having no ref to it in my project.
is there some internal dep on monk inside monkii?

thanks!

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'monk'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/dc/dev/rnd/qabot/botkit/config/botkit_mongo_storage.js:1:72)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
Program node server exited with code 1
```

```
botkit-express-demo@0.1.0 /Users/dc/dev/rnd/qabot/botkit
├── async@1.5.2
├─┬ body-parser@1.15.0
│ ├── bytes@2.2.0
│ ├── content-type@1.0.1
│ ├── depd@1.1.0
│ ├─┬ http-errors@1.4.0
│ │ ├── inherits@2.0.1
│ │ └── statuses@1.2.1
│ ├── iconv-lite@0.4.13
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.1.0
│ ├─┬ raw-body@2.1.5
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.11
│   └── media-typer@0.3.0
├─┬ botkit@0.0.5
│ ├─┬ jfs@0.2.6
│ │ ├── async@1.2.1
│ │ └── clone@1.0.2
│ ├── mustache@2.2.1
│ └─┬ ws@0.8.1
│   ├─┬ bufferutil@1.2.1
│   │ ├── bindings@1.2.1
│   │ └── nan@2.2.0
│   ├── options@0.0.6
│   ├── ultron@1.0.2
│   └── utf-8-validate@1.2.1
├── co@4.6.0
├─┬ debug@2.2.0
│ └── ms@0.7.1
├── dotenv@2.0.0
├── ejs@2.4.1
├── ent@2.2.0
├─┬ eslint@2.2.0
│ ├─┬ chalk@1.1.1
│ │ ├─┬ ansi-styles@2.2.0
│ │ │ └── color-convert@1.0.0
│ │ ├── escape-string-regexp@1.0.5
│ │ ├── has-ansi@2.0.0
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├─┬ concat-stream@1.5.1
│ │ ├─┬ readable-stream@2.0.5
│ │ │ ├── process-nextick-args@1.0.6
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ doctrine@1.2.0
│ │ ├── esutils@1.1.6
│ │ └── isarray@1.0.0
│ ├─┬ es6-map@0.1.3
│ │ ├── d@0.1.1
│ │ ├── es5-ext@0.10.11
│ │ ├── es6-iterator@2.0.0
│ │ ├── es6-set@0.1.4
│ │ ├── es6-symbol@3.0.2
│ │ └── event-emitter@0.3.4
│ ├─┬ escope@3.4.0
│ │ ├── es6-weak-map@2.0.1
│ │ └─┬ esrecurse@3.1.1
│ │   └── estraverse@3.1.0
│ ├─┬ espree@3.1.1
│ │ ├── acorn@3.0.4
│ │ └─┬ acorn-jsx@2.0.1
│ │   └── acorn@2.7.0
│ ├── estraverse@4.1.1
│ ├── estraverse-fb@1.3.1
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@1.2.4
│ │ ├─┬ flat-cache@1.0.10
│ │ │ ├─┬ del@2.2.0
│ │ │ │ ├─┬ globby@4.0.0
│ │ │ │ │ ├─┬ array-union@1.0.1
│ │ │ │ │ │ └── array-uniq@1.0.2
│ │ │ │ │ └── arrify@1.0.1
│ │ │ │ ├── is-path-cwd@1.0.0
│ │ │ │ ├─┬ is-path-in-cwd@1.0.0
│ │ │ │ │ └── is-path-inside@1.0.0
│ │ │ │ └── pify@2.3.0
│ │ │ ├── graceful-fs@4.1.3
│ │ │ ├── read-json-sync@1.1.1
│ │ │ └── write@0.2.1
│ │ └── object-assign@4.0.1
│ ├─┬ glob@6.0.4
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├─┬ minimatch@3.0.0
│ │ │ └─┬ brace-expansion@1.1.3
│ │ │   ├── balanced-match@0.3.0
│ │ │   └── concat-map@0.0.1
│ │ └── once@1.3.3
│ ├── globals@8.18.0
│ ├── ignore@2.2.19
│ ├─┬ inquirer@0.12.0
│ │ ├── ansi-escapes@1.1.1
│ │ ├── ansi-regex@2.0.0
│ │ ├─┬ cli-cursor@1.0.2
│ │ │ └─┬ restore-cursor@1.0.1
│ │ │   ├── exit-hook@1.1.1
│ │ │   └── onetime@1.1.0
│ │ ├── cli-width@2.1.0
│ │ ├── figures@1.4.0
│ │ ├─┬ readline2@1.0.1
│ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ ├── is-fullwidth-code-point@1.0.0
│ │ │ └── mute-stream@0.0.5
│ │ ├── run-async@0.1.0
│ │ ├── rx-lite@3.1.2
│ │ ├── string-width@1.0.1
│ │ └── through@2.3.8
│ ├─┬ is-my-json-valid@2.13.1
│ │ ├── generate-function@2.0.0
│ │ ├─┬ generate-object-property@1.2.0
│ │ │ └── is-property@1.0.2
│ │ ├── jsonpointer@2.0.0
│ │ └── xtend@4.0.1
│ ├─┬ is-resolvable@1.0.0
│ │ └── tryit@1.0.2
│ ├─┬ js-yaml@3.5.3
│ │ ├─┬ argparse@1.0.6
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@2.7.2
│ ├─┬ json-stable-stringify@1.0.1
│ │ └── jsonify@0.0.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ optionator@0.8.1
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@1.1.3
│ │ ├── levn@0.3.0
│ │ ├── prelude-ls@1.1.2
│ │ ├── type-check@0.3.2
│ │ └── wordwrap@1.0.0
│ ├── path-is-absolute@1.0.0
│ ├── path-is-inside@1.0.1
│ ├── pluralize@1.2.1
│ ├── progress@1.1.8
│ ├─┬ require-uncached@1.0.2
│ │ ├─┬ caller-path@0.1.0
│ │ │ └── callsites@0.2.0
│ │ └── resolve-from@1.0.1
│ ├── resolve@1.1.7
│ ├── shelljs@0.5.3
│ ├── strip-json-comments@1.0.4
│ ├─┬ table@3.7.8
│ │ ├── bluebird@3.3.3
│ │ ├── slice-ansi@0.0.4
│ │ ├── tv4@1.2.7
│ │ └── xregexp@3.1.0
│ ├── text-table@0.2.0
│ └─┬ user-home@2.0.0
│   └── os-homedir@1.0.1
├─┬ express@4.13.4
│ ├─┬ accepts@1.2.13
│ │ └── negotiator@0.5.3
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.1
│ ├── cookie@0.1.5
│ ├── cookie-signature@1.0.6
│ ├── escape-html@1.0.3
│ ├── etag@1.7.0
│ ├── finalhandler@0.4.1
│ ├── fresh@0.3.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.0.10
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.0.5
│ ├── qs@4.0.0
│ ├── range-parser@1.0.3
│ ├─┬ send@0.13.1
│ │ ├── destroy@1.0.4
│ │ ├── http-errors@1.3.1
│ │ └── mime@1.3.4
│ ├── serve-static@1.10.2
│ ├── utils-merge@1.0.0
│ └── vary@1.0.1
├─┬ google@1.5.0
│ └─┬ cheerio@0.19.0
│   ├─┬ css-select@1.0.0
│   │ ├── boolbase@1.0.0
│   │ ├── css-what@1.0.0
│   │ ├── domutils@1.4.3
│   │ └── nth-check@1.0.1
│   ├─┬ dom-serializer@0.1.0
│   │ └── domelementtype@1.1.3
│   ├── entities@1.1.1
│   ├─┬ htmlparser2@3.8.3
│   │ ├── domelementtype@1.3.0
│   │ ├── domhandler@2.3.0
│   │ ├── domutils@1.5.1
│   │ ├── entities@1.0.0
│   │ └── readable-stream@1.1.13
│   └── lodash@3.10.1
├── kerberos@0.0.18 extraneous
├── lodash@4.5.1
├── marked@0.3.5
├─┬ marked-terminal@1.6.1
│ ├─┬ cardinal@0.5.0
│ │ ├── ansicolors@0.2.1
│ │ └─┬ redeyed@0.5.0
│ │   └── esprima-fb@12001.1.0-dev-harmony-fb
│ ├─┬ cli-table@0.3.1
│ │ └── colors@1.0.3
│ ├─┬ lodash.assign@3.2.0
│ │ ├─┬ lodash._baseassign@3.2.0
│ │ │ └── lodash._basecopy@3.0.1
│ │ ├─┬ lodash._createassigner@3.1.1
│ │ │ ├── lodash._bindcallback@3.0.1
│ │ │ ├── lodash._isiterateecall@3.0.9
│ │ │ └── lodash.restparam@3.6.1
│ │ └─┬ lodash.keys@3.1.2
│ │   ├── lodash._getnative@3.9.1
│ │   ├── lodash.isarguments@3.0.7
│ │   └── lodash.isarray@3.0.4
│ └── node-emoji@0.1.0
├─┬ mongodb@2.0.55
│ ├── es6-promise@2.1.1
│ ├─┬ mongodb-core@1.2.31
│ │ └── bson@0.4.21
│ └─┬ readable-stream@1.0.31
│   ├── core-util-is@1.0.2
│   ├── isarray@0.0.1
│   └── string_decoder@0.10.31
├─┬ monkii@1.1.5
│ ├── mongoskin@2.0.3
│ └── mpromise@0.5.5
├── openurl@1.1.1
├─┬ request@2.69.0
│ ├── aws-sign2@0.6.0
│ ├─┬ aws4@1.2.1
│ │ └── lru-cache@2.7.3
│ ├── bl@1.0.3
│ ├── caseless@0.11.0
│ ├─┬ combined-stream@1.0.5
│ │ └── delayed-stream@1.0.0
│ ├── extend@3.0.0
│ ├── forever-agent@0.6.1
│ ├── form-data@1.0.0-rc3
│ ├─┬ har-validator@2.0.6
│ │ ├─┬ commander@2.9.0
│ │ │ └── graceful-readlink@1.0.1
│ │ └─┬ pinkie-promise@2.0.0
│ │   └── pinkie@2.0.4
│ ├─┬ hawk@3.1.3
│ │ ├── boom@2.10.1
│ │ ├── cryptiles@2.0.5
│ │ ├── hoek@2.16.3
│ │ └── sntp@1.0.9
│ ├─┬ http-signature@1.1.1
│ │ ├── assert-plus@0.2.0
│ │ ├─┬ jsprim@1.2.2
│ │ │ ├── extsprintf@1.0.2
│ │ │ ├── json-schema@0.2.2
│ │ │ └── verror@1.3.6
│ │ └─┬ sshpk@1.7.4
│ │   ├── asn1@0.2.3
│ │   ├─┬ dashdash@1.13.0
│ │   │ └── assert-plus@1.0.0
│ │   ├── ecc-jsbn@0.1.1
│ │   ├── jodid25519@1.0.2
│ │   ├── jsbn@0.1.0
│ │   └── tweetnacl@0.14.1
│ ├── is-typedarray@1.0.0
│ ├── isstream@0.1.2
│ ├── json-stringify-safe@5.0.1
│ ├─┬ mime-types@2.1.10
│ │ └── mime-db@1.22.0
│ ├── node-uuid@1.4.7
│ ├── oauth-sign@0.8.1
│ ├── qs@6.0.2
│ ├── stringstream@0.0.5
│ ├── tough-cookie@2.2.1
│ └── tunnel-agent@0.4.2
├─┬ slack-wrapi@0.1.3
│ └─┬ wrapi@0.1.6
│   ├─┬ request@2.65.0
│   │ ├─┬ http-signature@0.11.0
│   │ │ ├── asn1@0.1.11
│   │ │ ├── assert-plus@0.1.5
│   │ │ └── ctype@0.5.3
│   │ └── qs@5.2.0
│   └── urlpattern@0.1.0
└─┬ stackexchange@0.3.0
  ├─┬ devnull@0.0.12
  │ └── colors@0.6.2
  ├─┬ nconf@0.6.9
  │ ├── async@0.2.9
  │ ├── ini@1.3.4
  │ └─┬ optimist@0.6.0
  │   └── wordwrap@0.0.3
  ├─┬ request@2.21.0
  │ ├── aws-sign@0.3.0
  │ ├── cookie-jar@0.3.0
  │ ├── forever-agent@0.5.2
  │ ├─┬ form-data@0.0.8
  │ │ ├── async@0.2.10
  │ │ └─┬ combined-stream@0.0.7
  │ │   └── delayed-stream@0.0.5
  │ ├─┬ hawk@0.13.1
  │ │ ├─┬ boom@0.4.2
  │ │ │ └── hoek@0.9.1
  │ │ ├── cryptiles@0.2.2
  │ │ ├── hoek@0.8.5
  │ │ └─┬ sntp@0.2.4
  │ │   └── hoek@0.9.1
  │ ├─┬ http-signature@0.9.11
  │ │ ├── asn1@0.1.11
  │ │ ├── assert-plus@0.1.2
  │ │ └── ctype@0.5.2
  │ ├── json-stringify-safe@4.0.0
  │ ├── mime@1.2.11
  │ ├── oauth-sign@0.3.0
  │ ├── qs@0.6.6
  │ └── tunnel-agent@0.3.0
  └─┬ utile@0.2.1
    ├── async@0.2.10
    ├── deep-equal@1.0.1
    ├── i@0.3.4
    ├── ncp@0.4.2
    └─┬ rimraf@2.5.2
      └── glob@7.0.0

```

**Comment by dcsan** [comment]
this makes no sense to me either, so closing for now!

**Comment by ratson** [comment]
@dcsan do you have `node_modules/monk/` inside your project? You may try `npm prune` to see if it fixes the issue.
